os:
    - linux
    - osx
language: generic
sudo: required
dist: xenial

env:
  global:
    - SWIFT_VERSION=5.2
    
osx_image: xcode11.4
install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)";
script:
    - swift build && swift test;
